/**
 * Seed script – TulipDay Bollenstreek locaties & routes
 * Run: npx tsx scripts/seed-bollenstreek.ts
 */

import { createClient } from "@supabase/supabase-js";
import * as fs from "fs";
import * as path from "path";

// Laad .env.local handmatig (geen dotenv dependency nodig)
const envFile = path.resolve(__dirname, "../.env.local");
for (const line of fs.readFileSync(envFile, "utf-8").split("\n")) {
  const [k, ...v] = line.split("=");
  if (k && !k.startsWith("#")) process.env[k.trim()] = v.join("=").trim();
}

const sb = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
  { auth: { persistSession: false } }
);

// ─── Helpers ─────────────────────────────────────────────────────────────────

function slug(s: string) {
  return s.toLowerCase()
    .normalize("NFD").replace(/[\u0300-\u036f]/g, "")
    .replace(/\s+/g, "-")
    .replace(/[^a-z0-9-]/g, "")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
}

// ─── Locaties ─────────────────────────────────────────────────────────────────

const locations = [
  // ── Primaire attracties ──
  {
    title: "Keukenhof",
    slug: "keukenhof",
    category: "attraction",
    latitude: 52.2689, longitude: 4.5466,
    address: "Stationsweg 166A, Lisse",
    short_description: "Het meest beroemde bloemenpark ter wereld met 7 miljoen bollen op 32 hectare.",
    full_description: "Keukenhof is jaarlijks van medio maart tot begin mei open en trekt bezoekers van over de hele wereld. Het park bevat meer dan 800 soorten tulpen, narcissen en hyacinten, aangelegd in thematuinen langs slingerende paden. Combineer het bezoek met een fietsroute door de omliggende bollenvelden voor een complete beleving.\n\nOpen 2026: 19 maart – 10 mei.",
    bloom_status: "peak",
    photo_score: 5,
    crowd_score: 5,
    access_type: "public_access",
    best_visit_time: "Doordeweeks vroeg (voor 10:00) of in de laatste week van april",
    parking_info: "Betaald parkeren op eigen terrein. P+R via bus 854 vanuit Schiphol.",
    flower_type: "tulp, narcis, hyacint, dahlia",
    is_featured: true,
    is_active: true,
  },
  {
    title: "Tulip Experience Amsterdam",
    slug: "tulip-experience-amsterdam",
    category: "attraction",
    latitude: 52.2558, longitude: 4.5022,
    address: "Delfweg 113, Noordwijkerhout",
    short_description: "Experience-center, museum en showtuin op een actief bollenbedrijf met 4,7/5 beoordeling.",
    full_description: "Gelegen op een werkend bollenbedrijf aan de Delfweg in Noordwijkerhout. Naast de professionele showtuin kun je achter de schermen zien hoe bollenteelt in de praktijk werkt. De combinatie van museum, guided tours en weids uitzicht over de velden maakt dit een ideale stop voor gezinnen en fotografen.\n\nTravelers' Choice-award winnaar; 2.689+ beoordelingen op TripAdvisor.",
    bloom_status: "peak",
    photo_score: 5,
    crowd_score: 3,
    access_type: "public_access",
    best_visit_time: "Ochtend, vroeg april voor hyacinten; eind april voor tulpen",
    parking_info: "Gratis parkeren op het terrein.",
    flower_type: "tulp, hyacint, narcis",
    is_featured: true,
    is_active: true,
  },
  {
    title: "LAM Museum",
    slug: "lam-museum",
    category: "attraction",
    latitude: 52.2595, longitude: 4.5468,
    address: "Kasteel Keukenhof, Lisse",
    short_description: "Hedendaags kunstmuseum op Landgoed Keukenhof, perfect te combineren met een bezoek aan het park.",
    full_description: "Het LAM (Lisser Art Museum) is gevestigd in de eeuwenoude paardenstallen van Kasteel Keukenhof. De expositieruimten wisselen regelmatig van bezetting met werk van gerenommeerde hedendaagse kunstenaars. De setting – omringd door historisch landgoed en bloeiende tuinen – maakt het ook op slechte weerdagen de moeite waard.",
    bloom_status: "blooming",
    photo_score: 4,
    crowd_score: 2,
    access_type: "public_access",
    best_visit_time: "Doordeweeks; ideaal bij bewolkt weer",
    parking_info: "Parkeren bij Landgoed Keukenhof, gratis.",
    flower_type: null,
    is_featured: false,
    is_active: true,
  },
  {
    title: "De Tulperij",
    slug: "de-tulperij",
    category: "flower_field",
    latitude: 52.2176, longitude: 4.5026,
    address: "Oude Herenweg 16B, Voorhout",
    short_description: "Familiebollenbedrijf met showtuin en pluktuin, 4,6/5 op GetYourGuide.",
    full_description: "De Tulperij is een familiebedrijf in de vierde generatie. Bezokers kunnen door de kleurrijke showtuinen wandelen en eigen tulpen plukken. Kinderen leren hoe bollen worden geplant, gekweekt en geoogst. Het bedrijf ligt midden in de productievelden langs de Oude Herenweg in Voorhout.",
    bloom_status: "peak",
    photo_score: 4,
    crowd_score: 2,
    access_type: "public_access",
    best_visit_time: "Eind april, weekend",
    parking_info: "Gratis parkeren op het erf.",
    flower_type: "tulp",
    is_featured: true,
    is_active: true,
  },
  {
    title: "The Tulip Barn",
    slug: "the-tulip-barn",
    category: "photo_spot",
    latitude: 52.2973, longitude: 4.5739,
    address: "3e Loosterweg 130, Hillegom",
    short_description: "Populaire fotolocatie met spectaculaire rijen tulpen; perfect voor social content.",
    full_description: "The Tulip Barn is uitgegroeid tot een van de populairste fotoplekken in de Bollenstreek. Uitgestrekte rijen in felle kleuren, een authentieke schuur als decor en voldoende ruimte om rustig te fotograferen. Bezoekers van alle leeftijden komen hier specifiek voor de foto's.",
    bloom_status: "peak",
    photo_score: 5,
    crowd_score: 3,
    access_type: "public_access",
    best_visit_time: "Gouden uur – vroeg in de ochtend of vlak voor zonsondergang",
    parking_info: "Parkeren langs de weg; respecteer de omwonenden.",
    flower_type: "tulp",
    is_featured: true,
    is_active: true,
  },
  {
    title: "Landgoed Kasteel Keukenhof",
    slug: "landgoed-kasteel-keukenhof",
    category: "attraction",
    latitude: 52.2579, longitude: 4.5521,
    address: "Kasteel Keukenhof 1, Lisse",
    short_description: "200+ hectare historisch landgoed met kasteel, bos en tuinen – gratis toegankelijk.",
    full_description: "Het landgoed rondom Kasteel Keukenhof is een van de grootste aaneengesloten groengebieden in de Bollenstreek. Wandelpaden door het bos, zichtlijnen op het kasteel en rustiger dan het park zelf. Ideaal als aanvulling op een Keukenhof-bezoek of als op zichzelf staande wandelbestemming.",
    bloom_status: "blooming",
    photo_score: 4,
    crowd_score: 2,
    access_type: "public_access",
    best_visit_time: "Vroeg in de ochtend of late middag",
    parking_info: "Parkeren bij LAM Museum of langs Kasteel Keukenhof.",
    flower_type: "narcis, tulp",
    is_featured: false,
    is_active: true,
  },
  {
    title: "Museum De Zwarte Tulp",
    slug: "museum-de-zwarte-tulp",
    category: "attraction",
    latitude: 52.2573, longitude: 4.5580,
    address: "Grachtweg 2A, Lisse",
    short_description: "Specialistisch museum over de teelt, handel en veredeling van bloembollen.",
    full_description: "Museum De Zwarte Tulp vertelt het volledige verhaal achter de Nederlandse bloemenbollensector: van tulpenmanie in de 17e eeuw tot moderne veredeling. Interactieve tentoonstellingen maken het geschikt voor alle leeftijden. Op loopafstand van het centrum van Lisse.",
    bloom_status: "blooming",
    photo_score: 3,
    crowd_score: 2,
    access_type: "public_access",
    best_visit_time: "Ideaal bij regen of als aanvulling op een veldenbezoek",
    parking_info: "Parkeren in centrum Lisse, betaald.",
    flower_type: null,
    is_featured: false,
    is_active: true,
  },
  {
    title: "Keukenhofbos",
    slug: "keukenhofbos",
    category: "flower_field",
    latitude: 52.2682, longitude: 4.5476,
    address: "Keukenhofbos, Lisse",
    short_description: "Historisch bos direct naast Keukenhof, met meerdere rustige wandelpaden.",
    full_description: "Het Keukenhofbos is een eeuwenoud loofbos dat direct grenst aan het bloemenpark. In de lente bloeit de bosbodem met wilde narcissen en anemonen. De wandelpaden zijn gratis toegankelijk en bieden een rustiger alternatief voor de drukke parkomgeving.",
    bloom_status: "blooming",
    photo_score: 3,
    crowd_score: 1,
    access_type: "public_access",
    best_visit_time: "Vroege ochtend in april",
    parking_info: "Parkeer bij Keukenhof of langs Stationsweg.",
    flower_type: "narcis, wilde bloemen",
    is_featured: false,
    is_active: true,
  },
  {
    title: "Tulip Store Showtuin",
    slug: "tulip-store-showtuin",
    category: "flower_field",
    latitude: 52.2594, longitude: 4.5468,
    address: "Loosterweg Zuid 23, Lisse",
    short_description: "Meer dan 400 tulpensoorten op 5 minuten van Keukenhof.",
    full_description: "De Tulip Store Showtuin presenteert een indrukwekkende collectie van meer dan 400 tulpensoorten op een overzichtelijk perceel. Perfect voor kenners die specifieke rassen willen vergelijken of fotograferen. De winkel verkoopt bollen om mee naar huis te nemen.",
    bloom_status: "peak",
    photo_score: 4,
    crowd_score: 2,
    access_type: "public_access",
    best_visit_time: "Eind april, weekdag",
    parking_info: "Eigen parkeerterrein aanwezig.",
    flower_type: "tulp",
    is_featured: false,
    is_active: true,
  },
  // ── Dorpskernen & horeca ──
  {
    title: "Dorpshart Lisse – 't Vierkant",
    slug: "dorpshart-lisse-vierkant",
    category: "food",
    latitude: 52.2575, longitude: 4.5569,
    address: "'t Vierkant, Lisse",
    short_description: "Gezellige dorpskern van Lisse met restaurants, terrassen en winkels op loopafstand van Keukenhof.",
    full_description: "Het centrum van Lisse draait rond 't Vierkant, het dorpsplein met aantrekkelijke horeca en kleine winkels. Een logische tussenstop voor lunch of koffie tijdens een dag in de Bollenstreek. In het seizoen zijn er ook markten en evenementen.",
    bloom_status: "blooming",
    photo_score: 2,
    crowd_score: 3,
    access_type: "public_access",
    best_visit_time: "Lunchpauze, 12:00–14:00",
    parking_info: "Betaald parkeren in centrum; gratis buiten loopafstand.",
    flower_type: null,
    is_featured: false,
    is_active: true,
  },
  {
    title: "Pluktuin Lisse Centrum",
    slug: "pluktuin-lisse-centrum",
    category: "flower_field",
    latitude: 52.2573, longitude: 4.5575,
    address: "Centrum Lisse (bij Museum De Zwarte Tulp)",
    short_description: "Tijdelijke seizoenspluktuin in het centrum van Lisse, combineer met museumbezoek.",
    full_description: "Jaarlijks in het voorjaarsseizoen opent er een publieke pluktuin vlakbij Museum De Zwarte Tulp. Bezoekers mogen een eigen boeket samenstellen voor een klein bedrag. De pluktuin is populair bij gezinnen en een unieke aanvulling op een cultuurbezoek.",
    bloom_status: "peak",
    photo_score: 3,
    crowd_score: 2,
    access_type: "public_access",
    best_visit_time: "Doordeweeks, voor 12:00",
    parking_info: "Parkeren in centrum Lisse.",
    flower_type: "tulp, narcis",
    is_featured: false,
    is_active: true,
  },
  // ── Photo spots & corridors ──
  {
    title: "Delfweg Bloemencorridor",
    slug: "delfweg-bloemencorridor",
    category: "photo_spot",
    latitude: 52.2558, longitude: 4.5022,
    address: "Delfweg, Noordwijkerhout",
    short_description: "Lange corridor langs actieve bollenbedrijven met uitstekende fotomogelijkheden.",
    full_description: "De Delfweg in Noordwijkerhout is een van de mooiste rijroutes door de Bollenstreek. Aan weerszijden liggen professionele bollenpercelen in volle kleur. Tulip Experience Amsterdam is gevestigd langs deze weg, waardoor de stop zowel praktisch als visueel sterk is.",
    bloom_status: "peak",
    photo_score: 5,
    crowd_score: 2,
    access_type: "roadside_only",
    best_visit_time: "Vroeg ochtend of avondlicht",
    parking_info: "Langs de weg parkeren; respecteer inritten.",
    flower_type: "tulp, hyacint",
    is_featured: false,
    is_active: true,
  },
  {
    title: "3e Loosterweg Tulpenstrook",
    slug: "3e-loosterweg-tulpenstrook",
    category: "photo_spot",
    latitude: 52.2973, longitude: 4.5739,
    address: "3e Loosterweg, Hillegom",
    short_description: "Kleurrijke tulpenstrook waar ook The Tulip Barn ligt – een van de beste fotospots in Hillegom.",
    full_description: "De 3e Loosterweg in Hillegom loopt door een aaneengesloten zone met bollenpercelen. The Tulip Barn bevindt zich hier, maar ook de omliggende velden zijn fotogeniek. Rijd rustig over de weg en parkeer veilig voor het beste overzicht.",
    bloom_status: "peak",
    photo_score: 5,
    crowd_score: 3,
    access_type: "roadside_only",
    best_visit_time: "Gouden uur",
    parking_info: "Langs de weg; let op fietsers.",
    flower_type: "tulp",
    is_featured: false,
    is_active: true,
  },
  {
    title: "Loosterweg Zuid Tulpenvelden",
    slug: "loosterweg-zuid-tulpenvelden",
    category: "photo_spot",
    latitude: 52.2594, longitude: 4.5468,
    address: "Loosterweg Zuid, Lisse",
    short_description: "Weg door de Lissese bollenvelden, Tulip Store Showtuin ligt hier direct aan.",
    full_description: "Loosterweg Zuid loopt midden door de typische Lissese polderzone met aaneengesloten bollenpercelen. De Tulip Store Showtuin (nr. 23) biedt hier een officiële stop, maar ook de doorgaande weg zelf biedt prachtige doorzichten over de velden.",
    bloom_status: "peak",
    photo_score: 4,
    crowd_score: 2,
    access_type: "roadside_only",
    best_visit_time: "Vroeg in de ochtend",
    parking_info: "Langs de weg bij showtuin.",
    flower_type: "tulp",
    is_featured: false,
    is_active: true,
  },
  {
    title: "Oude Herenweg Bollenvelden",
    slug: "oude-herenweg-bollenvelden",
    category: "photo_spot",
    latitude: 52.2176, longitude: 4.5026,
    address: "Oude Herenweg, Voorhout",
    short_description: "Productievelden rondom De Tulperij in Voorhout – rustig en fotogeniek.",
    full_description: "De Oude Herenweg in Voorhout loopt door een zone met authentieke productievelden. De Tulperij (nr. 4) bevindt zich aan deze weg en biedt officiële toegang, maar de weg zelf geeft al mooie inkijkjes in de bollencultuur. Minder toeristisch dan Lisse, ideaal voor rustige fotosessies.",
    bloom_status: "peak",
    photo_score: 4,
    crowd_score: 1,
    access_type: "roadside_only",
    best_visit_time: "Doordeweeks vroeg in de ochtend",
    parking_info: "Langs de weg; bij De Tulperij gratis.",
    flower_type: "tulp, narcis",
    is_featured: false,
    is_active: true,
  },
  // ── Flower zones ──
  {
    title: "De Zilk – Bloembollenvelden",
    slug: "de-zilk-bloembollenvelden",
    category: "flower_field",
    latitude: 52.2975, longitude: 4.4987,
    address: "De Zilk",
    short_description: "Kleurrijke veldzone in het duinlandschap rond het dorp De Zilk.",
    full_description: "De Zilk is een klein dorp aan de rand van de duinen met een bijzondere ligging tussen bollenvelden en natuur. De combinatie van duinranden en kleurrijke tulpenpercelen maakt dit gebied aantrekkelijk voor wandelaars en fotografen die een rustiger alternatief zoeken voor de drukte rond Lisse.",
    bloom_status: "blooming",
    photo_score: 4,
    crowd_score: 1,
    access_type: "roadside_only",
    best_visit_time: "Ochtend, april",
    parking_info: "Langs de weg in De Zilk.",
    flower_type: "tulp, hyacint, narcis",
    is_featured: false,
    is_active: true,
  },
  {
    title: "Pluktuin Noordwijkerhout",
    slug: "pluktuin-noordwijkerhout",
    category: "flower_field",
    latitude: 52.2564, longitude: 4.5051,
    address: "Leeweg 8, Noordwijkerhout",
    short_description: "Officiële pluktuin langs de Leeweg in Noordwijkerhout.",
    full_description: "De pluktuin aan de Leeweg is een populaire stop voor gezinnen die zelf een vers tulpenboeket willen samenstellen. Het terrein ligt in een bredere bloemenzone met aangrenzende showtuinen en velden. Betalen per stengel of per boeket.",
    bloom_status: "peak",
    photo_score: 3,
    crowd_score: 2,
    access_type: "public_access",
    best_visit_time: "Doordeweeks, ochtend",
    parking_info: "Eigen parkeerruimte aanwezig.",
    flower_type: "tulp",
    is_featured: false,
    is_active: true,
  },
  {
    title: "Bollenveldenzone Lisse",
    slug: "bollenveldenzone-lisse",
    category: "flower_field",
    latitude: 52.2567, longitude: 4.5500,
    address: "Regio Lisse",
    short_description: "Het hart van de Bollenstreek: aaneengesloten percelen rondom de kern van Lisse.",
    full_description: "Lisse is de kern van de Nederlandse bloembollenteelt. Rondom het dorp liggen tientallen aaneengesloten percelen tulpen, narcissen en hyacinten. Via de fietsroutes van Keukenhof rijd je dwars door dit gebied. De velden zijn niet altijd publiek toegankelijk, maar langs de wegen zijn prachtige uitzichten.",
    bloom_status: "peak",
    photo_score: 4,
    crowd_score: 3,
    access_type: "roadside_only",
    best_visit_time: "Vroege ochtend in april",
    parking_info: "Langs diverse wegen in de omgeving.",
    flower_type: "tulp, hyacint, narcis",
    is_featured: false,
    is_active: true,
  },
  {
    title: "Bollenveldenzone Noordwijkerhout",
    slug: "bollenveldenzone-noordwijkerhout",
    category: "flower_field",
    latitude: 52.2565, longitude: 4.5058,
    address: "Regio Noordwijkerhout",
    short_description: "Uitgestrekte bollenvelden ten westen van Noordwijkerhout langs wandel- en fietsroutes.",
    full_description: "De bollenvelden rondom Noordwijkerhout zijn onderdeel van de officiële Flower Walk en meerdere fietsroutes. De combinatie van platte polderlandschappen, kleurrijke rijen en het nabijgelegen dorp maakt dit een aantrekkelijke zone voor actieve bezoekers.",
    bloom_status: "peak",
    photo_score: 4,
    crowd_score: 2,
    access_type: "roadside_only",
    best_visit_time: "Vroeg in de ochtend",
    parking_info: "Parkeren in Noordwijkerhout centrum.",
    flower_type: "tulp, hyacint",
    is_featured: false,
    is_active: true,
  },
  {
    title: "Bollenveldenzone Hillegom-Zuid",
    slug: "bollenveldenzone-hillegom-zuid",
    category: "flower_field",
    latitude: 52.2937, longitude: 4.5639,
    address: "Regio Hillegom-Zuid",
    short_description: "Tulpenzone ten zuiden van Hillegom, ook de thuisbasis van The Tulip Barn.",
    full_description: "De zone ten zuiden van Hillegom behoort tot de officiële Bollenstreek-corridor en omvat zowel productievelden als bezoekersattracties zoals The Tulip Barn. De Keukenhof-fietsroutes gaan ook door dit gebied.",
    bloom_status: "peak",
    photo_score: 4,
    crowd_score: 2,
    access_type: "roadside_only",
    best_visit_time: "Eind april",
    parking_info: "Langs diverse wegen; bij The Tulip Barn langs de weg.",
    flower_type: "tulp",
    is_featured: false,
    is_active: true,
  },
  // ── Historisch & cultuur ──
  {
    title: "Ruïne van Teylingen",
    slug: "ruine-van-teylingen",
    category: "attraction",
    latitude: 52.2186, longitude: 4.4934,
    address: "Ruïne van Teylingen, Voorhout",
    short_description: "Middeleeuwse kasteelruïne nabij Voorhout, direct verbonden met het Keukenhof-verhaal.",
    full_description: "De Ruïne van Teylingen is een 13e-eeuwse kasteelruïne op een heuveltje in het bollenveld. Het kasteel was onder andere de verblijfplaats van Jacoba van Beieren. In het voorjaar is de omgeving prachtig met bloeiende bollenvelden rondom de ruïne. Vrij toegankelijk.",
    bloom_status: "blooming",
    photo_score: 4,
    crowd_score: 1,
    access_type: "public_access",
    best_visit_time: "Middag, in combinatie met De Tulperij",
    parking_info: "Beperkt parkeren langs de weg.",
    flower_type: "tulp, narcis",
    is_featured: false,
    is_active: true,
  },
  {
    title: "JUB Holland",
    slug: "jub-holland",
    category: "attraction",
    latitude: 52.2570, longitude: 4.5060,
    address: "Gladiolenstraat 3, Noordwijkerhout",
    short_description: "Vierde generatie bloembollenspecialist met educatieve stop over veredeling en teelt.",
    full_description: "JUB Holland is een van de meest toonaangevende bloembolbedrijven in Nederland, al vier generaties lang actief in de veredeling van tulpen en andere bolgewassen. Bezoekers kunnen zien hoe nieuwe rassen worden ontwikkeld. Een interessante aanvulling voor liefhebbers die meer willen weten dan alleen de bloem.",
    bloom_status: "blooming",
    photo_score: 3,
    crowd_score: 1,
    access_type: "public_access",
    best_visit_time: "Doordeweeks",
    parking_info: "Eigen terrein.",
    flower_type: "tulp, lelie, narcis",
    is_featured: false,
    is_active: true,
  },
  // ── Bloemencorso ──
  {
    title: "Bloemencorso Bollenstreek – Corso Route",
    slug: "bloemencorso-bollenstreek",
    category: "attraction",
    latitude: 52.2565, longitude: 4.5058,
    address: "Start: Noordwijkerhout – Finish: Haarlem",
    short_description: "Een van de grootste voorjaarsevents van Nederland. In 2026 op zaterdag 18 april.",
    full_description: "Het Bloemencorso Bollenstreek is een jaarlijkse optocht van versierde praalwagens, volledig bekleed met verse bloemen. De route loopt van Noordwijkerhout door Lisse, Sassenheim en Hillegom naar Haarlem. De dag ervoor (vrijdagavond) rijdt het verlichte corso door Noordwijkerhout.\n\nDatum 2026: zaterdag 18 april.",
    bloom_status: "peak",
    photo_score: 5,
    crowd_score: 5,
    access_type: "public_access",
    best_visit_time: "Zaterdag 18 april 2026 – vroeg een plek langs de route innemen",
    parking_info: "Parkeer buiten de corsoroute en loop. P+R beschikbaar.",
    flower_type: "tulp, narcis, hyacint",
    is_featured: true,
    is_active: true,
  },
  {
    title: "Bloemenmozaïeken De Zilk",
    slug: "bloemenmozaieken-de-zilk",
    category: "attraction",
    latitude: 52.2975, longitude: 4.4987,
    address: "De Zilk",
    short_description: "Voorjaarsevent waarbij de dorpsbewoners kunstwerken maken van hyacinten.",
    full_description: "Tijdens het Bloemenmozaïeken-weekend versieren bewoners van De Zilk hun woonwijk met ingewikkelde mozaïeken gemaakt van kleurrijke hyacintenbollen. Het resultaat is elk jaar spectaculair en trekt bezoekers vanuit de hele regio.",
    bloom_status: "early",
    photo_score: 4,
    crowd_score: 3,
    access_type: "public_access",
    best_visit_time: "Hyacintenweekend, begin april",
    parking_info: "Parkeren in De Zilk, beperkt.",
    flower_type: "hyacint",
    is_featured: false,
    is_active: true,
  },
  // ── Dorpsbases ──
  {
    title: "Voorhout – Bloemendorp",
    slug: "voorhout-bloemendorp",
    category: "attraction",
    latitude: 52.2176, longitude: 4.5026,
    address: "Centrum Voorhout",
    short_description: "Pittoresk bloemendorp met De Tulperij, Ruïne van Teylingen en historisch centrum.",
    full_description: "Voorhout wordt officieel gepromoot als 'bloemendorp'. Het heeft een rustig historisch centrum met winkels en horeca, en is de uitvalsbasis voor De Tulperij en Ruïne van Teylingen. Minder druk dan Lisse, ideaal voor een ontspannen dagje in de bollenvelden.",
    bloom_status: "blooming",
    photo_score: 3,
    crowd_score: 1,
    access_type: "public_access",
    best_visit_time: "Doordeweeks",
    parking_info: "Gratis parkeren bij gemeenteparkeerplaatsen.",
    flower_type: null,
    is_featured: false,
    is_active: true,
  },
];

// ─── Routes ───────────────────────────────────────────────────────────────────

const routes = [
  {
    title: "Keukenhof Fietsroute Blauw (5 km)",
    slug: "keukenhof-fietsroute-blauw",
    description: "De kortste officiële Keukenhof-fietsroute. Ideaal voor een korte uitje of als warming-up. Loopt langs de directe omgeving van het park.",
    route_type: "bike",
    distance_km: 5,
    duration_minutes: 25,
    cover_image_url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900",
    is_featured: false,
    is_active: true,
  },
  {
    title: "Keukenhof Fietsroute Paars (10 km)",
    slug: "keukenhof-fietsroute-paars",
    description: "Officiële Keukenhof-route van 10 km door de bollenvelden rondom Lisse. Goed te combineren met een parkbezoek.",
    route_type: "bike",
    distance_km: 10,
    duration_minutes: 45,
    cover_image_url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900",
    is_featured: false,
    is_active: true,
  },
  {
    title: "Keukenhof Fietsroute Groen (15 km)",
    slug: "keukenhof-fietsroute-groen",
    description: "Een uitgebreidere route van 15 km, populair bij e-bikers. Rijdt door de poldervelden ten zuiden van Lisse.",
    route_type: "bike",
    distance_km: 15,
    duration_minutes: 65,
    cover_image_url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900",
    is_featured: true,
    is_active: true,
  },
  {
    title: "Keukenhof Fietsroute Rood (25 km)",
    slug: "keukenhof-fietsroute-rood",
    description: "De uitgebreidste officiële Keukenhof-fietsroute van 25 km. Voor fanatiekere fietsers die de hele Bollenstreek willen verkennen.",
    route_type: "bike",
    distance_km: 25,
    duration_minutes: 110,
    cover_image_url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900",
    is_featured: false,
    is_active: true,
  },
  {
    title: "Tulip Bike Tour (10 km)",
    slug: "tulip-bike-tour-10km",
    description: "Gratis self-guided route van 10 km langs werkende bollenbedrijven in de Keukenhof-regio. Download de kaart en rijd op eigen tempo.",
    route_type: "bike",
    distance_km: 10,
    duration_minutes: 50,
    cover_image_url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900",
    is_featured: true,
    is_active: true,
  },
  {
    title: "Bollenstreek Flower Route",
    slug: "bollenstreek-flower-route",
    description: "De officiële Flower Route door de Bollenstreek langs de mooiste velden, showtuinen en dorpen. Volg de Flower Map voor het beste seizoensoverzicht.",
    route_type: "bike",
    distance_km: 35,
    duration_minutes: 150,
    cover_image_url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900",
    is_featured: true,
    is_active: true,
  },
  {
    title: "Noordwijkerhout Flower Walk (18 km)",
    slug: "noordwijkerhout-flower-walk",
    description: "Officiële bloemenwandeling van 18 km langs velden, showtuinen en dorpsstops. In te korten tot 12 km. Vertrekt vanuit Victoriberg in Noordwijkerhout.",
    route_type: "walk",
    distance_km: 18,
    duration_minutes: 270,
    cover_image_url: "https://images.unsplash.com/photo-1490750967868-88df5691cc8c?w=900",
    is_featured: true,
    is_active: true,
  },
  {
    title: "Bloemenwandeling Lisse (8 km)",
    slug: "bloemenwandeling-lisse",
    description: "Officiële wandeling van 8 km door de Lissese bollenvelden, langs Keukenhofbos en het landgoed. Goed bewegwijzerd en geschikt voor alle leeftijden.",
    route_type: "walk",
    distance_km: 8,
    duration_minutes: 120,
    cover_image_url: "https://images.unsplash.com/photo-1490750967868-88df5691cc8c?w=900",
    is_featured: false,
    is_active: true,
  },
  {
    title: "Tulip Cycle Tour",
    slug: "tulip-cycle-tour",
    description: "Samenwerking van Tulip Experience en Rent-a-Bike voor een begeleide fietstour door de bollenvelden rondom Noordwijkerhout. Inclusief fietshuur en gids.",
    route_type: "bike",
    distance_km: 20,
    duration_minutes: 180,
    cover_image_url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900",
    is_featured: false,
    is_active: true,
  },
  {
    title: "Gezinsroute Bollenstreek",
    slug: "gezinsroute-bollenstreek",
    description: "Een ontspannen gezinsroute langs De Tulperij, Keukenhof en de Tulip Store Showtuin. Korte afstanden, veel te zien en kindvriendelijke stops.",
    route_type: "family",
    distance_km: 22,
    duration_minutes: 240,
    cover_image_url: "https://images.unsplash.com/photo-1490750967868-88df5691cc8c?w=900",
    is_featured: true,
    is_active: true,
  },
  {
    title: "Fotografen Route Bollenstreek",
    slug: "fotografen-route-bollenstreek",
    description: "De ultieme fotoroute langs The Tulip Barn, Delfweg, Loosterweg Zuid en Oude Herenweg. Bewust gericht op de mooiste lichtmomenten en minst drukke locaties.",
    route_type: "photo",
    distance_km: 30,
    duration_minutes: 240,
    cover_image_url: "https://images.unsplash.com/photo-1490750967868-88df5691cc8c?w=900",
    is_featured: true,
    is_active: true,
  },
];

// ─── Seed ─────────────────────────────────────────────────────────────────────

async function seed() {
  console.log("🌷 TulipDay seed gestart...\n");

  // Locaties
  console.log(`📍 ${locations.length} locaties invoegen...`);
  for (const loc of locations) {
    const { error } = await sb.from("locations").upsert(loc, { onConflict: "slug" });
    if (error) {
      console.error(`  ✗ ${loc.title}: ${error.message}`);
    } else {
      console.log(`  ✓ ${loc.title}`);
    }
  }

  // Routes
  console.log(`\n🗺  ${routes.length} routes invoegen...`);
  for (const route of routes) {
    const { error } = await sb.from("routes").upsert(route, { onConflict: "slug" });
    if (error) {
      console.error(`  ✗ ${route.title}: ${error.message}`);
    } else {
      console.log(`  ✓ ${route.title}`);
    }
  }

  console.log("\n✅ Seed klaar!");
}

seed().catch(console.error);
