-- ============================================================
-- SEED: Tulipday bollenvelden lijst (174 locaties)
-- Alle velden starten met bloom_status='blooming', is_featured=false
-- Tom past bloeistatus handmatig aan via het admin-paneel
-- ============================================================

insert into locations
  (id, title, slug, category, latitude, longitude, address,
   short_description, flower_type, bloom_status,
   photo_score, crowd_score, access_type,
   parking_info, best_visit_time, image_url, is_featured, is_active)
values
  (gen_random_uuid(), 'Frank Van Borselenlaan 5', 'frank-van-borselenlaan-5', 'flower_field',
   52.2290556, 4.5124167,
   'frank van borselenlaan 5', 'Bollenveld langs de Frank in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Frank Van Borselenlaan 4', 'frank-van-borselenlaan-4', 'flower_field',
   52.2293056, 4.5099444,
   'frank van borselenlaan 4', 'Bollenveld langs de Frank in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Van Den Berch Van Heemstedeweg 2', 'van-den-berch-van-heemstedeweg-2', 'flower_field',
   52.2266389, 4.5068611,
   'van den berch van heemstedeweg 2', 'Bollenveld langs de Van in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Frank Van Borselenlaan 1', 'frank-van-borselenlaan-1', 'flower_field',
   52.2324722, 4.5150833,
   'frank van borselenlaan 1', 'Bollenveld langs de Frank in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Frank Van Borselenlaan 2', 'frank-van-borselenlaan-2', 'flower_field',
   52.231, 4.51325,
   'frank van borselenlaan 2', 'Bollenveld langs de Frank in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Frank Van Borselenlaan 3', 'frank-van-borselenlaan-3', 'flower_field',
   52.2299444, 4.5112778,
   'frank van borselenlaan 3', 'Bollenveld langs de Frank in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Van Den Berch Van Heemstedeweg 1', 'van-den-berch-van-heemstedeweg-1', 'flower_field',
   52.2291389, 4.5030278,
   'van den berch van heemstedeweg 1', 'Bollenveld langs de Van in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Prinsenweg 4', 'prinsenweg-4', 'flower_field',
   52.2310278, 4.502,
   'prinsenweg 4', 'Bollenveld langs de Prinsenweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Prinsenweg 3', 'prinsenweg-3', 'flower_field',
   52.232, 4.5037222,
   'prinsenweg 3', 'Bollenveld langs de Prinsenweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Prinsenweg 2', 'prinsenweg-2', 'flower_field',
   52.2340833, 4.5066667,
   'prinsenweg 2', 'Bollenveld langs de Prinsenweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Prinsenweg 1', 'prinsenweg-1', 'flower_field',
   52.2357222, 4.5096944,
   'prinsenweg 1', 'Bollenveld langs de Prinsenweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Teylingerdreef 2', 'teylingerdreef-2', 'flower_field',
   52.2234722, 4.5008333,
   'teylingerdreef 2', 'Bollenveld langs de Teylingerdreef in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Eikenhorstlaan 1', 'eikenhorstlaan-1', 'flower_field',
   52.22575, 4.5052222,
   'eikenhorstlaan 1', 'Bollenveld langs de Eikenhorstlaan in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Teylingerdreef 1', 'teylingerdreef-1', 'flower_field',
   52.2270556, 4.50075,
   'teylingerdreef 1', 'Bollenveld langs de Teylingerdreef in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Jacoba Van Beierenweg 3', 'jacoba-van-beierenweg-3', 'flower_field',
   52.2324167, 4.4965556,
   'jacoba van beierenweg 3', 'Bollenveld langs de Jacoba in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Jacoba Van Beierenweg 2', 'jacoba-van-beierenweg-2', 'flower_field',
   52.2336667, 4.4993611,
   'jacoba van beierenweg 2', 'Bollenveld langs de Jacoba in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Jacoba Van Beierenweg 1', 'jacoba-van-beierenweg-1', 'flower_field',
   52.2366667, 4.5040278,
   'jacoba van beierenweg 1', 'Bollenveld langs de Jacoba in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Leidsestraat 3', 'leidsestraat-3', 'flower_field',
   52.2818611, 4.5726389,
   'leidsestraat 3', 'Bollenveld langs de Leidsestraat in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Leidsestraat 2', 'leidsestraat-2', 'flower_field',
   52.2798889, 4.5717778,
   'leidsestraat 2', 'Bollenveld langs de Leidsestraat in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Leidsestraat 1', 'leidsestraat-1', 'flower_field',
   52.2738611, 4.5683056,
   'leidsestraat 1', 'Bollenveld langs de Leidsestraat in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Heereweg Lis 8', 'heereweg-lis-8', 'flower_field',
   52.2696389, 4.5599167,
   'heereweg lis 8', 'Bollenveld langs de Heereweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Zwartelaan 2', 'zwartelaan-2', 'flower_field',
   52.2738056, 4.5616111,
   'zwartelaan 2', 'Bollenveld langs de Zwartelaan in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Zwartelaan 1', 'zwartelaan-1', 'flower_field',
   52.2757778, 4.5565833,
   'zwartelaan 1', 'Bollenveld langs de Zwartelaan in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Veenenburgerlaan 5', 'veenenburgerlaan-5', 'flower_field',
   52.2884167, 4.5739722,
   'veenenburgerlaan 5', 'Bollenveld langs de Veenenburgerlaan in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Veenenburgerlaan 4', 'veenenburgerlaan-4', 'flower_field',
   52.2885556, 4.5685833,
   'veenenburgerlaan 4', 'Bollenveld langs de Veenenburgerlaan in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Veenenburgerlaan 3', 'veenenburgerlaan-3', 'flower_field',
   52.2873611, 4.5624444,
   'veenenburgerlaan 3', 'Bollenveld langs de Veenenburgerlaan in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Veenenburgerlaan 2', 'veenenburgerlaan-2', 'flower_field',
   52.2862222, 4.559,
   'veenenburgerlaan 2', 'Bollenveld langs de Veenenburgerlaan in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Veenenburgerlaan 1', 'veenenburgerlaan-1', 'flower_field',
   52.2852222, 4.5576111,
   'veenenburgerlaan 1', 'Bollenveld langs de Veenenburgerlaan in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Loosterweg Noord 4', 'loosterweg-noord-4', 'flower_field',
   52.2820278, 4.5538611,
   'loosterweg noord 4', 'Bollenveld langs de Loosterweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Loosterweg Noord 3', 'loosterweg-noord-3', 'flower_field',
   52.2798889, 4.55225,
   'loosterweg noord 3', 'Bollenveld langs de Loosterweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Loosterweg Noord 2', 'loosterweg-noord-2', 'flower_field',
   52.27725, 4.5495,
   'loosterweg noord 2', 'Bollenveld langs de Loosterweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Loosterweg Noord 1', 'loosterweg-noord-1', 'flower_field',
   52.275, 4.5471389,
   'loosterweg noord 1', 'Bollenveld langs de Loosterweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), '3e Loosterweg 3', '3e-loosterweg-3', 'flower_field',
   52.2881667, 4.5644444,
   '3e loosterweg 3', 'Bollenveld langs de 3e in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), '3e Loosterweg 2', '3e-loosterweg-2', 'flower_field',
   52.2915, 4.56175,
   '3e loosterweg 2', 'Bollenveld langs de 3e in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), '3e Loosterweg 1', '3e-loosterweg-1', 'flower_field',
   52.2937222, 4.5626111,
   '3e loosterweg 1', 'Bollenveld langs de 3e in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Wilheminalaan 1', 'wilheminalaan-1', 'flower_field',
   52.2956389, 4.5663056,
   'wilheminalaan 1', 'Bollenveld langs de Wilheminalaan in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Beeklaan Hillegom 2', 'beeklaan-hillegom-2', 'flower_field',
   52.297, 4.5572222,
   'beeklaan hillegom 2', 'Bollenveld langs de Beeklaan in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Beeklaan Hillegom 1', 'beeklaan-hillegom-1', 'flower_field',
   52.2961944, 4.5600278,
   'beeklaan hillegom 1', 'Bollenveld langs de Beeklaan in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Zuider Leidsevaart 4', 'zuider-leidsevaart-4', 'flower_field',
   52.2937222, 4.5505833,
   'zuider leidsevaart 4', 'Bollenveld langs de Zuider in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Zuider Leidsevaart 3', 'zuider-leidsevaart-3', 'flower_field',
   52.2893056, 4.5466667,
   'zuider leidsevaart 3', 'Bollenveld langs de Zuider in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Zuider Leidsevaart 2', 'zuider-leidsevaart-2', 'flower_field',
   52.2851944, 4.5431111,
   'zuider leidsevaart 2', 'Bollenveld langs de Zuider in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Zuider Leidsevaart 1', 'zuider-leidsevaart-1', 'flower_field',
   52.2803056, 4.5387778,
   'zuider leidsevaart 1', 'Bollenveld langs de Zuider in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Delfweg 2', 'delfweg-2', 'flower_field',
   52.2807222, 4.5344444,
   'delfweg 2', 'Bollenveld langs de Delfweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Delfweg 1', 'delfweg-1', 'flower_field',
   52.2835556, 4.5328333,
   'delfweg 1', 'Bollenveld langs de Delfweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Pastoorslaan 3', 'pastoorslaan-3', 'flower_field',
   52.3033056, 4.5790833,
   'pastoorslaan 3', 'Bollenveld langs de Pastoorslaan in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Pastoorslaan 2', 'pastoorslaan-2', 'flower_field',
   52.3049444, 4.5739722,
   'pastoorslaan 2', 'Bollenveld langs de Pastoorslaan in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Pastoorslaan 1', 'pastoorslaan-1', 'flower_field',
   52.3065278, 4.5702222,
   'pastoorslaan 1', 'Bollenveld langs de Pastoorslaan in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), '1e Loosterweg 2', '1e-loosterweg-2', 'flower_field',
   52.3070833, 4.5694722,
   '1e loosterweg 2', 'Bollenveld langs de 1e in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), '1e Loosterweg 1', '1e-loosterweg-1', 'flower_field',
   52.3101944, 4.5715,
   '1e loosterweg 1', 'Bollenveld langs de 1e in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Nieuweweg 2', 'nieuweweg-2', 'flower_field',
   52.3137222, 4.5805,
   'nieuweweg 2', 'Bollenveld langs de Nieuweweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Nieuweweg 1', 'nieuweweg-1', 'flower_field',
   52.3135278, 4.5759722,
   'nieuweweg 1', 'Bollenveld langs de Nieuweweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Noorder Leidsevaart 4', 'noorder-leidsevaart-4', 'flower_field',
   52.3123611, 4.5664722,
   'noorder leidsevaart 4', 'Bollenveld langs de Noorder in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), '2e Doodweg 2', '2e-doodweg-2', 'flower_field',
   52.3184722, 4.5656944,
   '2e doodweg 2', 'Bollenveld langs de 2e in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), '2e Doodweg 1', '2e-doodweg-1', 'flower_field',
   52.3168333, 4.5643889,
   '2e doodweg 1', 'Bollenveld langs de 2e in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Provincialeweg 4', 'provincialeweg-4', 'flower_field',
   52.3158611, 4.5741389,
   'provincialeweg 4', 'Bollenveld langs de Provincialeweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Provincialeweg 3', 'provincialeweg-3', 'flower_field',
   52.3138889, 4.5670556,
   'provincialeweg 3', 'Bollenveld langs de Provincialeweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Provincialeweg 2', 'provincialeweg-2', 'flower_field',
   52.3132222, 4.5600556,
   'provincialeweg 2', 'Bollenveld langs de Provincialeweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Provincialeweg 1', 'provincialeweg-1', 'flower_field',
   52.312, 4.5533333,
   'provincialeweg 1', 'Bollenveld langs de Provincialeweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Noorder Leidsevaart 3', 'noorder-leidsevaart-3', 'flower_field',
   52.3074444, 4.5624167,
   'noorder leidsevaart 3', 'Bollenveld langs de Noorder in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Noorder Leidsevaart 2', 'noorder-leidsevaart-2', 'flower_field',
   52.3038333, 4.5594722,
   'noorder leidsevaart 2', 'Bollenveld langs de Noorder in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Noorder Leidsevaart 1', 'noorder-leidsevaart-1', 'flower_field',
   52.3003889, 4.5566389,
   'noorder leidsevaart 1', 'Bollenveld langs de Noorder in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Hoogduinweg 3', 'hoogduinweg-3', 'flower_field',
   52.2983056, 4.5526389,
   'hoogduinweg 3', 'Bollenveld langs de Hoogduinweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Hoogduinweg 2', 'hoogduinweg-2', 'flower_field',
   52.2996667, 4.5478333,
   'hoogduinweg 2', 'Bollenveld langs de Hoogduinweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Hoogduinweg 1', 'hoogduinweg-1', 'flower_field',
   52.30125, 4.5407222,
   'hoogduinweg 1', 'Bollenveld langs de Hoogduinweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Zilkerbinnenweg 5', 'zilkerbinnenweg-5', 'flower_field',
   52.2991111, 4.5424167,
   'zilkerbinnenweg 5', 'Bollenveld langs de Zilkerbinnenweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Zilkerbinnenweg 4', 'zilkerbinnenweg-4', 'flower_field',
   52.2973056, 4.5416389,
   'zilkerbinnenweg 4', 'Bollenveld langs de Zilkerbinnenweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Zilkerbinnenweg 3', 'zilkerbinnenweg-3', 'flower_field',
   52.2928611, 4.5362222,
   'zilkerbinnenweg 3', 'Bollenveld langs de Zilkerbinnenweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Zilkerbinnenweg 2', 'zilkerbinnenweg-2', 'flower_field',
   52.2900833, 4.5344444,
   'zilkerbinnenweg 2', 'Bollenveld langs de Zilkerbinnenweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Zilkerbinnenweg 1', 'zilkerbinnenweg-1', 'flower_field',
   52.2879444, 4.5328611,
   'zilkerbinnenweg 1', 'Bollenveld langs de Zilkerbinnenweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Oude Herenweg 5', 'oude-herenweg-5', 'flower_field',
   52.2413056, 4.5266667,
   'oude herenweg 5', 'Bollenveld langs de Oude in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Oude Herenweg 4', 'oude-herenweg-4', 'flower_field',
   52.2403056, 4.5255,
   'oude herenweg 4', 'Bollenveld langs de Oude in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Oude Herenweg 3', 'oude-herenweg-3', 'flower_field',
   52.2381944, 4.5229167,
   'oude herenweg 3', 'Bollenveld langs de Oude in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Oude Herenweg 2', 'oude-herenweg-2', 'flower_field',
   52.2369722, 4.5211667,
   'oude herenweg 2', 'Bollenveld langs de Oude in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Oude Herenweg 1', 'oude-herenweg-1', 'flower_field',
   52.2356111, 4.5191944,
   'oude herenweg 1', 'Bollenveld langs de Oude in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Teylingenlaan 3', 'teylingenlaan-3', 'flower_field',
   52.2375556, 4.5107778,
   'teylingenlaan 3', 'Bollenveld langs de Teylingenlaan in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Teylingenlaan 2', 'teylingenlaan-2', 'flower_field',
   52.2360278, 4.5136667,
   'teylingenlaan 2', 'Bollenveld langs de Teylingenlaan in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Teylingerlaan 1', 'teylingerlaan-1', 'flower_field',
   52.2340833, 4.5173056,
   'teylingerlaan 1', 'Bollenveld langs de Teylingerlaan in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Carolus Clusiuslaan 1', 'carolus-clusiuslaan-1', 'flower_field',
   52.2321389, 4.5249167,
   'carolus clusiuslaan 1', 'Bollenveld langs de Carolus in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Heereweg Lis 7', 'heereweg-lis-7', 'flower_field',
   52.2344444, 4.5322222,
   'heereweg lis 7', 'Bollenveld langs de Heereweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Heereweg Lis 6', 'heereweg-lis-6', 'flower_field',
   52.2368889, 4.5345556,
   'heereweg lis 6', 'Bollenveld langs de Heereweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Heereweg Lis 5', 'heereweg-lis-5', 'flower_field',
   52.2386389, 4.5359167,
   'heereweg lis 5', 'Bollenveld langs de Heereweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Heereweg Lis 4', 'heereweg-lis-4', 'flower_field',
   52.2404167, 4.5373889,
   'heereweg lis 4', 'Bollenveld langs de Heereweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Heereweg Lis 3', 'heereweg-lis-3', 'flower_field',
   52.2457778, 4.5418333,
   'heereweg lis 3', 'Bollenveld langs de Heereweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Heereweg Lis 2', 'heereweg-lis-2', 'flower_field',
   52.2493333, 4.5446944,
   'heereweg lis 2', 'Bollenveld langs de Heereweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Heereweg Lis 1', 'heereweg-lis-1', 'flower_field',
   52.2515556, 4.5462222,
   'heereweg lis 1', 'Bollenveld langs de Heereweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Westelijke Randweg 2', 'westelijke-randweg-2', 'flower_field',
   52.2550556, 4.5471111,
   'westelijke randweg 2', 'Bollenveld langs de Westelijke in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Westelijke Randweg 1', 'westelijke-randweg-1', 'flower_field',
   52.2610278, 4.5491389,
   'westelijke randweg 1', 'Bollenveld langs de Westelijke in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Stationsweg 1', 'stationsweg-1', 'flower_field',
   52.2650556, 4.5486667,
   'stationsweg 1', 'Bollenveld langs de Stationsweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Van Lyndenweg 2', 'van-lyndenweg-2', 'flower_field',
   52.2648333, 4.5465,
   'van lyndenweg 2', 'Bollenveld langs de Van in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Van Lyndenweg 1', 'van-lyndenweg-1', 'flower_field',
   52.26175, 4.5439167,
   'van lyndenweg 1', 'Bollenveld langs de Van in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Spekkenlaan 2', 'spekkenlaan-2', 'flower_field',
   52.2599167, 4.5379444,
   'spekkenlaan 2', 'Bollenveld langs de Spekkenlaan in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Spekkenlaan 1', 'spekkenlaan-1', 'flower_field',
   52.2600556, 4.5347778,
   'spekkenlaan 1', 'Bollenveld langs de Spekkenlaan in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Loosterweg Zuid 3', 'loosterweg-zuid-3', 'flower_field',
   52.2591667, 4.5314167,
   'loosterweg zuid 3', 'Bollenveld langs de Loosterweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Loosterweg Zuid 2', 'loosterweg-zuid-2', 'flower_field',
   52.2575556, 4.5294167,
   'loosterweg zuid 2', 'Bollenveld langs de Loosterweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Loosterweg Zuid 1', 'loosterweg-zuid-1', 'flower_field',
   52.25325, 4.5264722,
   'loosterweg zuid 1', 'Bollenveld langs de Loosterweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Achterweg Zuid 5', 'achterweg-zuid-5', 'flower_field',
   52.2549167, 4.54375,
   'achterweg zuid 5', 'Bollenveld langs de Achterweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Achterweg Zuid 4', 'achterweg-zuid-4', 'flower_field',
   52.2531111, 4.5423333,
   'achterweg zuid 4', 'Bollenveld langs de Achterweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Achterweg Zuid 3', 'achterweg-zuid-3', 'flower_field',
   52.2483889, 4.5390833,
   'achterweg zuid 3', 'Bollenveld langs de Achterweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Achterweg Zuid 2', 'achterweg-zuid-2', 'flower_field',
   52.2459444, 4.5346667,
   'achterweg zuid 2', 'Bollenveld langs de Achterweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Achterweg Zuid 1', 'achterweg-zuid-1', 'flower_field',
   52.2439167, 4.5317778,
   'achterweg zuid 1', 'Bollenveld langs de Achterweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Akervoorderlaan 2', 'akervoorderlaan-2', 'flower_field',
   52.2404722, 4.5319722,
   'akervoorderlaan 2', 'Bollenveld langs de Akervoorderlaan in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Akervoorderlaan 1', 'akervoorderlaan-1', 'flower_field',
   52.2425, 4.5276667,
   'akervoorderlaan 1', 'Bollenveld langs de Akervoorderlaan in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Essenlaan 3', 'essenlaan-3', 'flower_field',
   52.247, 4.5340278,
   'essenlaan 3', 'Bollenveld langs de Essenlaan in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Essenlaan 2', 'essenlaan-2', 'flower_field',
   52.2489167, 4.5302778,
   'essenlaan 2', 'Bollenveld langs de Essenlaan in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Essenlaan 1', 'essenlaan-1', 'flower_field',
   52.2508333, 4.5273056,
   'essenlaan 1', 'Bollenveld langs de Essenlaan in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Loosterweg 5', 'loosterweg-5', 'flower_field',
   52.2512222, 4.5231667,
   'loosterweg 5', 'Bollenveld langs de Loosterweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Loosterweg 4', 'loosterweg-4', 'flower_field',
   52.2484167, 4.5188056,
   'loosterweg 4', 'Bollenveld langs de Loosterweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Johan Speelmanweg 1', 'johan-speelmanweg-1', 'flower_field',
   52.2458611, 4.5183611,
   'johan speelmanweg 1', 'Bollenveld langs de Johan in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Loosterweg 3', 'loosterweg-3', 'flower_field',
   52.2448056, 4.5141111,
   'loosterweg 3', 'Bollenveld langs de Loosterweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Loosterweg 2', 'loosterweg-2', 'flower_field',
   52.2408611, 4.5101667,
   'loosterweg 2', 'Bollenveld langs de Loosterweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Loosterweg 1', 'loosterweg-1', 'flower_field',
   52.2387778, 4.5077778,
   'loosterweg 1', 'Bollenveld langs de Loosterweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Sgravendamseweg 3', 'sgravendamseweg-3', 'flower_field',
   52.23975, 4.5033611,
   'sgravendamseweg 3', 'Bollenveld langs de Sgravendamseweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Sgravendamseweg 2', 'sgravendamseweg-2', 'flower_field',
   52.2485556, 4.4879722,
   'sgravendamseweg 2', 'Bollenveld langs de Sgravendamseweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Sgravendamseweg 1', 'sgravendamseweg-1', 'flower_field',
   52.2495833, 4.484,
   'sgravendamseweg 1', 'Bollenveld langs de Sgravendamseweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Leidsevaart 5', 'leidsevaart-5', 'flower_field',
   52.2360278, 4.4824722,
   'leidsevaart 5', 'Bollenveld langs de Leidsevaart in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Leidsevaart 4', 'leidsevaart-4', 'flower_field',
   52.2348056, 4.4807222,
   'leidsevaart 4', 'Bollenveld langs de Leidsevaart in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Leidsevaart 3', 'leidsevaart-3', 'flower_field',
   52.2332222, 4.4783611,
   'leidsevaart 3', 'Bollenveld langs de Leidsevaart in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Leidsevaart 2', 'leidsevaart-2', 'flower_field',
   52.2304444, 4.4741667,
   'leidsevaart 2', 'Bollenveld langs de Leidsevaart in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Leidsevaart 1', 'leidsevaart-1', 'flower_field',
   52.2237778, 4.4733056,
   'leidsevaart 1', 'Bollenveld langs de Leidsevaart in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Schippersvaartweg 2', 'schippersvaartweg-2', 'flower_field',
   52.2571667, 4.5094167,
   'schippersvaartweg 2', 'Bollenveld langs de Schippersvaartweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Schippersvaartweg 1', 'schippersvaartweg-1', 'flower_field',
   52.2590278, 4.5046667,
   'schippersvaartweg 1', 'Bollenveld langs de Schippersvaartweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Via Nova 2', 'via-nova-2', 'flower_field',
   52.2614444, 4.5050833,
   'via nova 2', 'Bollenveld langs de Via in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Via Nova 1', 'via-nova-1', 'flower_field',
   52.2658611, 4.5028056,
   'via nova 1', 'Bollenveld langs de Via in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Achterweg Noordwijk 1', 'achterweg-noordwijk-1', 'flower_field',
   52.2205556, 4.4440278,
   'achterweg noordwijk 1', 'Bollenveld langs de Achterweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Herenweg Nw 3', 'herenweg-nw-3', 'flower_field',
   52.2248333, 4.4427778,
   'herenweg nw 3', 'Bollenveld langs de Herenweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Herenweg Nw 2', 'herenweg-nw-2', 'flower_field',
   52.2196111, 4.4391944,
   'herenweg nw 2', 'Bollenveld langs de Herenweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Herenweg Nw 1', 'herenweg-nw-1', 'flower_field',
   52.2167778, 4.4386389,
   'herenweg nw 1', 'Bollenveld langs de Herenweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Zwarteweg Noordwijk', 'zwarteweg-noordwijk', 'flower_field',
   52.2208611, 4.4373889,
   'zwarteweg noordwijk', 'Bollenveld langs de Zwarteweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Het Laantje 3', 'het-laantje-3', 'flower_field',
   52.2279444, 4.4274444,
   'het laantje 3', 'Bollenveld langs de Het in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Het Laantje 2', 'het-laantje-2', 'flower_field',
   52.2289722, 4.4309722,
   'het laantje 2', 'Bollenveld langs de Het in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Het Laantje 1', 'het-laantje-1', 'flower_field',
   52.231, 4.4350833,
   'het laantje 1', 'Bollenveld langs de Het in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Beeklaan Noordwijk 2', 'beeklaan-noordwijk-2', 'flower_field',
   52.2341389, 4.4371389,
   'beeklaan noordwijk 2', 'Bollenveld langs de Beeklaan in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Beeklaan Noordwijk 1', 'beeklaan-noordwijk-1', 'flower_field',
   52.2363333, 4.4350833,
   'beeklaan noordwijk 1', 'Bollenveld langs de Beeklaan in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Nieuwe Zeeweg Noordwijk', 'nieuwe-zeeweg-noordwijk', 'flower_field',
   52.2383889, 4.4419722,
   'nieuwe zeeweg noordwijk', 'Bollenveld langs de Nieuwe in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Leeweg 6', 'leeweg-6', 'flower_field',
   52.2303611, 4.465,
   'leeweg 6', 'Bollenveld langs de Leeweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Leeweg 5', 'leeweg-5', 'flower_field',
   52.2341389, 4.4668611,
   'leeweg 5', 'Bollenveld langs de Leeweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Leeweg 4', 'leeweg-4', 'flower_field',
   52.2371389, 4.4689722,
   'leeweg 4', 'Bollenveld langs de Leeweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Leeweg 3', 'leeweg-3', 'flower_field',
   52.2398889, 4.4710556,
   'leeweg 3', 'Bollenveld langs de Leeweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Leeweg 2', 'leeweg-2', 'flower_field',
   52.2428056, 4.4734722,
   'leeweg 2', 'Bollenveld langs de Leeweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Leeweg 1', 'leeweg-1', 'flower_field',
   52.2481944, 4.4827222,
   'leeweg 1', 'Bollenveld langs de Leeweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Bronsgeesterweg 3', 'bronsgeesterweg-3', 'flower_field',
   52.2329167, 4.4620833,
   'bronsgeesterweg 3', 'Bollenveld langs de Bronsgeesterweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Bronsgeesterweg 2', 'bronsgeesterweg-2', 'flower_field',
   52.2366389, 4.4654444,
   'bronsgeesterweg 2', 'Bollenveld langs de Bronsgeesterweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Bronsgeesterweg 1', 'bronsgeesterweg-1', 'flower_field',
   52.2405278, 4.4688611,
   'bronsgeesterweg 1', 'Bollenveld langs de Bronsgeesterweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Langervelderweg 2', 'langervelderweg-2', 'flower_field',
   52.27375, 4.4973056,
   'langervelderweg 2', 'Bollenveld langs de Langervelderweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Langervelderweg 1', 'langervelderweg-1', 'flower_field',
   52.2709444, 4.4951667,
   'langervelderweg 1', 'Bollenveld langs de Langervelderweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Duinweg 3', 'duinweg-3', 'flower_field',
   52.262, 4.4555278,
   'duinweg 3', 'Bollenveld langs de Duinweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Duinweg 2', 'duinweg-2', 'flower_field',
   52.2590556, 4.4521944,
   'duinweg 2', 'Bollenveld langs de Duinweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Duinweg 1', 'duinweg-1', 'flower_field',
   52.2511944, 4.4497778,
   'duinweg 1', 'Bollenveld langs de Duinweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Northgodreef 1', 'northgodreef-1', 'flower_field',
   52.2480833, 4.4513056,
   'northgodreef 1', 'Bollenveld langs de Northgodreef in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Westeinde 6', 'westeinde-6', 'flower_field',
   52.2495833, 4.4655833,
   'westeinde 6', 'Bollenveld langs de Westeinde in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Westeinde 5', 'westeinde-5', 'flower_field',
   52.2512778, 4.4680556,
   'westeinde 5', 'Bollenveld langs de Westeinde in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Westeinde 4', 'westeinde-4', 'flower_field',
   52.2616389, 4.4779444,
   'westeinde 4', 'Bollenveld langs de Westeinde in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Westeinde 3', 'westeinde-3', 'flower_field',
   52.2601667, 4.475,
   'westeinde 3', 'Bollenveld langs de Westeinde in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Westeinde 2', 'westeinde-2', 'flower_field',
   52.2586111, 4.4722778,
   'westeinde 2', 'Bollenveld langs de Westeinde in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Westeinde 1', 'westeinde-1', 'flower_field',
   52.2536667, 4.47275,
   'westeinde 1', 'Bollenveld langs de Westeinde in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Gooweg 1', 'gooweg-1', 'flower_field',
   52.2545278, 4.4799444,
   'gooweg 1', 'Bollenveld langs de Gooweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Schulpweg 2', 'schulpweg-2', 'flower_field',
   52.2601111, 4.4838333,
   'schulpweg 2', 'Bollenveld langs de Schulpweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Schulpweg 1', 'schulpweg-1', 'flower_field',
   52.2649722, 4.4748333,
   'schulpweg 1', 'Bollenveld langs de Schulpweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Kraaierslaan 1', 'kraaierslaan-1', 'flower_field',
   52.2695833, 4.4746944,
   'kraaierslaan 1', 'Bollenveld langs de Kraaierslaan in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Langervelderlaan 1', 'langervelderlaan-1', 'flower_field',
   52.28125, 4.4882222,
   'langervelderlaan 1', 'Bollenveld langs de Langervelderlaan in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Vogelaarsdreef 2', 'vogelaarsdreef-2', 'flower_field',
   52.29325, 4.4980556,
   'vogelaarsdreef 2', 'Bollenveld langs de Vogelaarsdreef in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Vogelaarsdreef 1', 'vogelaarsdreef-1', 'flower_field',
   52.2951667, 4.50325,
   'vogelaarsdreef 1', 'Bollenveld langs de Vogelaarsdreef in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Wilgendam 1', 'wilgendam-1', 'flower_field',
   52.2853056, 4.4997778,
   'wilgendam 1', 'Bollenveld langs de Wilgendam in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Wilgendam 2', 'wilgendam-2', 'flower_field',
   52.29025, 4.4952222,
   'wilgendam 2', 'Bollenveld langs de Wilgendam in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'De Boender 2', 'de-boender-2', 'flower_field',
   52.2887778, 4.5008056,
   'de boender 2', 'Bollenveld langs de De in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'De Boender 1', 'de-boender-1', 'flower_field',
   52.2909444, 4.5068611,
   'de boender 1', 'Bollenveld langs de De in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Duinschoten 4', 'duinschoten-4', 'flower_field',
   52.2903611, 4.5129167,
   'duinschoten 4', 'Bollenveld langs de Duinschoten in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Duinschoten 3', 'duinschoten-3', 'flower_field',
   52.2871389, 4.5081111,
   'duinschoten 3', 'Bollenveld langs de Duinschoten in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Duinschoten 2', 'duinschoten-2', 'flower_field',
   52.2848056, 4.5048611,
   'duinschoten 2', 'Bollenveld langs de Duinschoten in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Duinschoten 1', 'duinschoten-1', 'flower_field',
   52.2823333, 4.5004722,
   'duinschoten 1', 'Bollenveld langs de Duinschoten in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Boekhorsterweg 1', 'boekhorsterweg-1', 'flower_field',
   52.2762222, 4.5003611,
   'boekhorsterweg 1', 'Bollenveld langs de Boekhorsterweg in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Oosterduinen 3', 'oosterduinen-3', 'flower_field',
   52.2768889, 4.5111389,
   'oosterduinen 3', 'Bollenveld langs de Oosterduinen in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Oosterduinen 2', 'oosterduinen-2', 'flower_field',
   52.2814444, 4.5152778,
   'oosterduinen 2', 'Bollenveld langs de Oosterduinen in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true),
  (gen_random_uuid(), 'Oosterduinen 1', 'oosterduinen-1', 'flower_field',
   52.2868889, 4.5204444,
   'oosterduinen 1', 'Bollenveld langs de Oosterduinen in de Bollenstreek.',
   'tulip', 'blooming', 4, 3, 'roadside_only',
   'Beperkt parkeren langs de weg. Fiets aanbevolen.',
   'Vroeg in de ochtend voor de mooiste foto''s.',
   NULL, false, true)
ON CONFLICT (slug) DO NOTHING;
